### ISSUE TITLE
Incorrect target name

### ISSUE THREAD

**Issue by thenol** [openml/automlbenchmark#456]
Hi, I am trying to run a test for flaml framework on openml dataset sylvine, whose true target name is 'class', which does not match  the y benchmark passed to flaml. I think the reason maybe the sort of features in OpenmlDataset class.

**Comment by PGijsbers** [comment]
Hi! Thanks for reporting the issue. It looks to be a problem caused by a switch in `openml`  from arff to parquet format. The new parquet datasets do not observe the same order of features as the ARFF files and the OpenML provided feature meta-data do, which messes with our indexing. We'll work on resolving this issue.

**Comment by PGijsbers** [comment]
While this warrants an issue for `openml-python` / openml server, I do think we should consider a sanity check / indexing by name instead. @sebhrusen ?

**Comment by Innixma** [comment]
Just saw this, it appears to be the same issue I am facing in #457

**Comment by PGijsbers** [comment]
This _should_ be resolved for the datasets connected to the tasks in benchmarking suites 269 and 271 (the remainder of the datasets still need updating as we prioritized the suites). The `constantpredictor` successfully produced results on the first fold of each task of the benchmark.
You will need to clear your cache (see where it is located with `openml.config.cache_directory`), at least the erroneous datasets (in the `org/openml/www/datasets`  subdirectory).

**Comment by sebhrusen** [comment]
@PGijsbers do you confirm this is due to an old issue with `openml-python` and that there's nothing to fix on our side? or that it was fixed on our side months ago? any issue/PR related with that fix? thx

**Comment by PGijsbers** [comment]
This was caused by the recent conversion of datasets from arff to parquet on the openml server. The script that was used for the conversion altered the dataset column order (and even dropped certain columns), which made the meta-data out of sync. `openml-python` was already forward-compatible with the change to parquet, which unfortunately meant the changes were immediately propagated to the users. Our fix was to correct the conversion script and rerun it so that the parquet file columns again match the arff ones.

In principle, there is nothing to fix on our side. As a precaution we could consider indexing by column name instead of index.

**Comment by Innixma** [comment]
> As a precaution we could consider indexing by column name instead of index.

Assuming the benchmark is committed to having column names, this seems a lot safer. Many nasty bugs can sneak through when using position rather than column name.

**Comment by Innixma** [comment]
The datasets look mostly good now, although for some reason I am still getting strange errors in `MIP-2016-regression`, so it may still need to be fixed.

`openml.org/t/359947`

`ResultError: could not convert string to float: 'ok'`

**Comment by PGijsbers** [comment]
I can confirm that for this dataset the parquet column order still does not match that of the ARFF file... passing this along.

**Comment by PGijsbers** [comment]
The issue should be resolved now (constant predictor works).
